sanity-io/sdk

- packages/core/typedoc.json
- packages/react/typedoc.json
Removes custom entrypoint names for typedoc
Pretty wild!
N/A
> fix(docs): remove custom docs entrypoint names

- .circleci/config.yml
Enables automatic upload of bundles to both staging and production Google Cloud Storage buckets during the CircleCI build process. This automates the deployment pipeline by uncommenting and expanding the previously commented-out bundle upload step.
- Verify that the environment variables for both staging and production are correctly referenced
- Check that the `upload:bundles` script is properly implemented in the package.json
- Ensure the CircleCI environment has the necessary GCS credentials configured
Tested by running the CircleCI pipeline with the updated configuration and verifying that bundles are correctly uploaded to both staging and production buckets.
> chore(ci): upload bundle to staging bucket

- apps/kitchensink-react/package.json
- packages/@repo/config-eslint/package.json
- packages/react/package.json
- pnpm-lock.yaml
It seems like only `babel-plugin-react-compiler` is on the RC. This PR updates `eslint-plugin-react-compiler` and `react-compiler-runtime` as well 🙌 
Did I miss a spot?
Existing tests are enough. There aren't any actual changes in `react-compiler-runtime` for example, but seeing as `@sanity/ui`, `react-rx` etc are now on the RC by moving the sdk we reduce the amount of duplicated instances of `react-compiler-runtime` in `node_modules`.
For `eslint-plugin-react-compiler` it's only the linting step, which should stay on the same version as the `babel-plugin-react-compiler` to ensure that actionable errors and warnings show up during linting as the babel plugin itself isn't setup to show warnings in this repo.
> fix(deps): move react compiler to RC

- packages/core/src/document/documentConstants.ts
- packages/core/src/document/sharedListener.ts
- packages/core/src/query/queryStoreConstants.ts
Ups API versions now that text query search is GA.
The very extensive changes
Search worked when I tried manually
> fix(core): bump default api versions

- apps/kitchensink-react/src/DocumentCollection/DocumentPreview.tsx
- apps/kitchensink-react/src/DocumentCollection/DocumentProjectionRoute.tsx
- apps/kitchensink-react/src/DocumentCollection/OrgDocumentExplorerRoute.tsx
- packages/react/guides/0-Migration-Guide.md
- packages/react/guides/Document-Handles.md
- packages/react/guides/Typescript.md
- packages/react/internal-guides/Advanced-Resource-Management.md
- packages/react/src/_exports/sdk-react.ts
- packages/react/src/hooks/document/useDocument.ts
- packages/react/src/hooks/documents/useDocuments.ts
- packages/react/src/hooks/paginatedDocuments/usePaginatedDocuments.ts
- packages/react/src/hooks/preview/useDocumentPreview.test.tsx
- packages/react/src/hooks/preview/useDocumentPreview.tsx
- packages/react/src/hooks/projection/useDocumentProjection.test.tsx
- packages/react/src/hooks/projection/useDocumentProjection.ts
Renamed hooks for better clarity and consistency:
- `usePreview` → `useDocumentPreview`
- `useProjection` → `useDocumentProjection`
Also renamed associated types to match:
- `UsePreviewOptions` → `useDocumentPreviewOptions`
- `UsePreviewResults` → `useDocumentPreviewResults`
- `UseProjectionOptions` → `useDocumentProjectionOptions`
- `UseProjectionResults` → `useDocumentProjectionResults`
These changes make the hook names more explicit about their purpose and align with the existing naming pattern of document-related hooks like `useDocument` and `useDocumentEvent`.
- Check that all imports and references to the renamed hooks have been updated
- Verify that the renamed types are properly exported
- Ensure documentation references have been updated to reflect the new names
- Confirm that …
> chore!: rename useProjection to useDocumentProjection & rename usePreview to useDocumentPreview

- apps/kitchensink-react/src/DocumentCollection/DocumentEditorRoute.tsx
- apps/kitchensink-react/src/DocumentCollection/MultiResourceRoute.tsx
- apps/kitchensink-react/src/DocumentCollection/OrgDocumentExplorerRoute.tsx
- packages/react/guides/0-Migration-Guide.md
- packages/react/src/hooks/document/useDocument.test.ts
- packages/react/src/hooks/document/useDocument.ts
- packages/react/src/hooks/document/useEditDocument.ts
This PR updates the `useDocument` hook to return data under a `data` property for consistency across the SDK. This change aligns with patterns used in other hooks like `useQuery` and `useDocumentProjection`.
Key changes:
- Added wrapper hook pattern to normalize return structure
- Updated all examples in documentation and test files
- Modified type definitions to reflect new return shape
- Added migration guide section for the breaking change
1. **Migration Guide Section**  
Verify the new section in `packages/react/guides/0-Migration-Guide.md`:
- Clear before/after examples
- Accurate TypeScript examples
- Consistent formatting with other migration sections
2. **Test Updates**  
Check `useDocument.test.ts` for:
- Updated assertions checking `.data` property
- Maintenance of existing test …
> refactor(react): update useDocument to return `data`

- apps/kitchensink-react/eslint.config.mjs
Added `sanity.types.ts` to the ESLint ignore list in the kitchensink-react app. This file is generated by Sanity TypeGen and should not be linted.
Check that the ESLint configuration properly ignores the `sanity.types.ts` file, which is now listed under the "Ignore files for Sanity TypeGen" comment.
Verified that ESLint no longer attempts to lint the `sanity.types.ts` file when running linting commands.
> chore: eslint ignore auto-generated typegen file

- packages/core/src/preview/util.ts
- packages/core/src/projection/util.ts
In their respective stores, reviews and projections coalesce draft and query results and return a "status" object that includes params for when the draft was last edited and when the published version was last edited, so people could indicate the status of the document. However, they were also using the `drafts` perspective, which does the coalescing in the query result so everything was mistakenly "published" from the status perspective.
This restores the raw perspective. 
It's a larger question about what we want to do about "status". This may only get more complex once we introduce perspectives. Are we going to return the version document and the published document?
Should we just use the `drafts` perspective and get the data some other way?
> fix(core): use raw perspective for functions that coalesce draft/published

- apps/kitchensink-react/package.json
- apps/kitchensink-react/sanity-typegen.json
- packages/core/package.json
- packages/core/src/document/applyDocumentActions.ts
- packages/core/src/document/documentStore.test.ts
- packages/core/src/document/documentStore.ts
- packages/core/src/projection/getProjectionState.ts
- packages/core/src/projection/resolveProjection.ts
- packages/core/src/query/queryStore.ts
- packages/react/guides/Typescript.md
- packages/react/package.json
- packages/react/src/hooks/document/useApplyDocumentActions.ts
- packages/react/src/hooks/document/useDocument.test.ts
- packages/react/src/hooks/document/useDocument.ts
- packages/react/src/hooks/document/useEditDocument.ts
- packages/react/src/hooks/projection/useDocumentProjection.ts
- packages/react/src/hooks/query/useQuery.ts
- pnpm-lock.yaml
This PR refactors the codebase to align with the new experimental Typegen configuration and updated type definitions.
Key changes include:
- Updated experimental package versions for `groq` (to `3.88.1-typegen-experimental.0`) and `@sanity/cli` (to `3.88.1-typegen-experimental.0`).
- Refactored `sanity-typegen.json` to use the `unstable_schemas` array and the `schemaId` property (combining `projectId` and `dataset`) instead of the previous `schemas`, `projectId`, and `dataset` structure. This simplifies the configuration for multiple schemas.
- Updated internal type usages from `SanityDocumentResult` to `SanityDocument`.
- Replaced `DatasetScoped` with `SchemaOrigin` for type branding.
- Replaced `DocumentTypeScoped` with `ProjectionBase` for projection result branding.
- Updated the …
> refactor: update to latest typegen-experimental

- .lintstagedrc.mjs
- apps/kitchensink-react/.gitignore
- apps/kitchensink-react/package.json
- apps/kitchensink-react/sanity-typegen.json
- apps/kitchensink-react/sanity.cli.ts
- apps/kitchensink-react/sanity.config.ts
- apps/kitchensink-react/src/App.tsx
- apps/kitchensink-react/src/DocumentCollection/MultiResourceRoute.tsx
- apps/kitchensink-react/src/main.tsx
- pnpm-lock.yaml
This PR makes various changes to allow the Kitchensink to easily run as Dashboard application. That includes things required by the Sanity runtime (a `sanity.cli.ts` file, App.tsx as a default export) as well as removing things that would cause errors in the dashboard -- like referencing projects and documents from different organizations.
Most of this should be pretty minimal. I think the styled-components dep is necessary since we're using @sanity/ui but feel free to call me out on that.
The Kitchensink is now deployed [here](https://www.sanity.io/@oSyH1iET5/application/cbhuuqhkp6sevhpreoh0so8s). Please don't re-deploy, I have a downstream PR that I deployed.
^ Graphite chose this GIF for me, thank you Graphite
> fix(kitchensink): allow kitchensink to be deployed and used in dashboard

- apps/kitchensink-react/src/DocumentCollection/DocumentPreview.tsx
- packages/core/src/preview/previewQuery.test.ts
- packages/core/src/preview/previewQuery.ts
- packages/core/src/preview/previewStore.ts
- packages/core/src/projection/projectionQuery.test.ts
- packages/core/src/projection/projectionQuery.ts
- packages/core/src/projection/subscribeToStateAndFetchBatches.test.ts
- packages/react/guides/0-Migration-Guide.md
Renamed `status` to `_status` in preview and projection results to prevent collisions with user-defined fields and follow the convention of using underscore prefix for system attributes. This change affects the `PreviewValue` interface and both projection and preview results.
Added migration documentation for this breaking change in the migration guide.
- Verify that all references to the `status` field in preview and projection results have been updated to `_status`
- Check the migration guide to ensure it clearly explains the change and provides appropriate examples
- Confirm that all tests have been updated to reflect this change
Updated all relevant tests to use `_status` instead of `status`. Tests now verify that preview and projection results correctly include the renamed field.
> fix!: change `status` to `_status` in projection and preview

- apps/kitchensink-react/src/App.tsx
- packages/react/src/_exports/sdk-react.ts
- packages/react/src/hooks/dashboard/useDashboardNavigate.test.ts
- packages/react/src/hooks/dashboard/useDashboardNavigate.ts
Add a new `useDashboardNavigate` hook that enables navigation functionality based on dashboard messages -- this is required for cases when you are in an application that you have favorited and click on the favorites item in the Dashboard sidebar. There may be additional occasions where this will be necessary.
The hook is now exported from the SDK React package and implemented in the kitchen sink app to demonstrate its usage with React Router.
Does this implementation feel like good DX?
The single test provides 100% test coverage. You can try the hook out manually by doing the following:
1. Go to the [dashboard interactions in deployed Kitchensink in Dashboard](https://www.sanity.io/@oSyH1iET5/application/cbhuuqhkp6sevhpreoh0so8s/document-dashboard-interactions).
2. Favorite a document.
3. …
> feat(react): add dashboard navigate function

- packages/core/src/_exports/index.ts
- packages/core/src/releases/getPerspectiveState.test.ts
- packages/core/src/releases/getPerspectiveState.ts
- packages/core/src/releases/releasesStore.test.ts
- packages/core/src/releases/releasesStore.ts
This PR updates the release perspective handling in @sdk/core to match the behavior in the Studio -- it seems like better DX that these behaviors are the same across applications. Additionally, it exports the `ReleasePerspective` type and filters out archived and published releases from the active releases list.
- The changes to `getPerspectiveState.ts` and `releasesStore.ts` to ensure the sorting and filtering logic is correct
- The updated tests in `getPerspectiveState.test.ts` and `releasesStore.test.ts` to verify the new behavior
- The export of the `ReleasePerspective` type in the core exports
Updated existing tests to account for the reversed order of releases. The tests now correctly expect the releases to be in reverse order to match the UI behavior elsewhere.
> fix(core): align release order with studio release order

- package.json
- packages/e2e/.gitignore
- packages/e2e/package.json
- packages/e2e/playwright.config.ts
- packages/e2e/tests/react/e2e.spec.ts
- pnpm-lock.yaml
- turbo.json
- vitest.workspace.ts
This PR contains the results of the initial setup for Playwright. This follows [Vercel’s recommended setup](https://www.youtube.com/watch?v=bsE1VJn1HeU) for Playwright projects in Turbo backed monorepos; I found [a pretty comprehensive walkthrough](https://www.youtube.com/watch?v=NYLMm3oAdTs) that seemed to align.
- Adds a new E2E package with the Playwright dependency and the starter Playwright config (with a config option pointing at the React tests mentioned next)
- Adds a stub at `packages/e2e/tests/react` — we'll put our React E2E tests here; could optionally create `packages/e2e/tests/core` for the Core SDK E2E tests (if any)
- Adds an `e2e` script at the monorepo's root
- Adds an `e2e` task to the Turbo config; I confess I have no idea what this does as I was just following the …
> feat: set up Playwright

- packages/core/guides/AuthenticationGuide.md
Moved and renamed the authentication guide from `packages/core/src/auth/Auth Guide.md` to `packages/core/guides/AuthenticationGuide.md` for better organization. Updated terminology throughout the document, changing "Authentication Channels" to "Authentication Types" for clarity. Made minor text improvements including clarifying the standalone authentication mode and adding a note about the Studio Mode no longer being under construction.
- Verify the new location and filename make sense in the project structure
- Check that terminology changes from "channels" to "types" are consistent
- Confirm the updated descriptions for authentication types are accurate, especially the standalone mode clarifications
Manual verification of the document's content and location is sufficient as this is a …
> chore: move the authentication guide to be in the docs

- packages/react/package.json
- pnpm-lock.yaml
Upgraded `@sanity/comlink` from version 3.0.2 to 3.0.4 to ensure we're using the latest version with bug fixes and improvements.
- Verify that the package.json dependency update is correct
- Check that the pnpm-lock.yaml changes reflect the proper version update
The change is a minor version update to a dependency, which should not introduce breaking changes. The package's existing tests should cover functionality that depends on this library.
> fix(deps): update dependency @sanity/comlink to ^3.0.4

- .github/workflows/release-please.yml
This PR updates the release-please workflow to exclude the e2e directory from both the build and publish steps. This ensures that e2e tests are not included in the build process or published to NPM.
- Verify that the `--filter=!./e2e` flag is correctly added to both the build command and the publish command
- Check that the publish command now includes the same filters as the build command for consistency
The changes were tested by verifying that the workflow correctly excludes e2e tests during the build and publish process.
> chore: prevent the release of e2e package

- packages/core/src/document/patchOperations.test.ts
- packages/core/src/document/patchOperations.ts
Fix negative index handling in JSONMatch `insert` patch operations to be compliant with content-lake behavior.
Previously, negative indexes in `insert` operations (before/after/replace) were not being properly converted to positive indexes before processing keyed segments, leading to incorrect insertion behavior. This change ensures that negative indexes like `[-1]` are correctly resolved to their positive equivalents before any further path resolution.
**Changes introduced:**
- Fixed negative index conversion in `insert` operations to happen before keyed segment lookups
- Updated test expectations to reflect correct behavior (negative indexes should resolve to actual array positions, not special append/prepend behavior)
- Corrected a bug in the "after" operation where negative index …
> fix(core): consider negative indexes for inserts

- packages/@repo/e2e/package.json
- packages/@repo/e2e/src/fixtures.ts
- packages/@repo/e2e/src/helpers/clients.ts
- packages/@repo/e2e/src/helpers/documents.ts
- pnpm-lock.yaml
This PR adds Sanity client and document management utilities to the E2E testing framework. These fixtures can create (or bulk creates) test documents and lets devs access Sanity clients, along with cleanup functionality to ensure test documents are removed after tests complete.
- The new fixtures in `fixtures.ts` that expose `createDocuments` and `clients` to tests, and cleans up after each test.
- The document management helpers in `helpers/documents.ts` for creating and cleaning up test documents
- The client configuration in `helpers/clients.ts` that sets up connections to primary and secondary datasets
Unfortunately, none of this is used in this particular PR. If you want to test this out manually, I'd go to #560 and do the following:
1. pull down the branch
2. run `pnpm dev:e2e`
3. …
> test(e2e): create fixtures for creating documents and deleting them at the end of a run

- .github/workflows/e2e.yml
- apps/kitchensink-react/package.json
- apps/kitchensink-react/playwright.config.ts
- package.json
- packages/@repo/e2e/src/helpers/getE2EEnv.ts
- packages/@repo/e2e/src/helpers/loadEnvFiles.ts
- packages/@repo/e2e/src/index.ts
- packages/@repo/e2e/src/scripts/cleanup-datasets.ts
- pnpm-lock.yaml
- turbo.json
This PR adds a GitHub Actions workflow for running end-to-end tests across multiple browsers. The workflow runs Playwright tests on Chromium, Firefox, and WebKit browsers for both PRs and the main branch, with attempts at caching of browser binaries to improve performance.
The implementation includes:
- New GitHub workflow file for E2E tests with proper concurrency settings
- Configuration for running tests in CI environment using build+preview instead of dev server
- Added browser matrix to run tests in parallel across different browsers
- Improved error reporting for missing environment variables
- The new `.github/workflows/e2e.yml` workflow configuration
- Changes to the Playwright configuration to support CI environments
- Updates to E2E helpers for better error handling and …
> test(e2e): create initial e2e github action

- packages/core/src/document/patchOperations.test.ts
- packages/core/src/document/patchOperations.ts
Fix array element removal order in JSONMatch `unset` operations to prevent index shifting issues.
When unsetting multiple array elements using range expressions (e.g., `items[1:3]`), the elements were being removed in forward order, causing subsequent removals to target incorrect indices due to array shifting. This change ensures elements are removed in reverse order (from highest to lowest index) to maintain index stability during the removal process.
**Changes introduced:**
- Added `.reverse()` to the unset operation to process matches in reverse order
- Updated test expectations to reflect correct behavior when unsetting array ranges
- Added explanatory comments about why reverse order is necessary
**Example fix:**
- Input: `{items: [1, 2, 3, 4, 5]}`
- Unset path: `items[1:3]` (should …
> fix(core): correct element removal order in `unset`s

- packages/react/src/hooks/preview/useDocumentPreview.tsx
Adds remarks for `useDocumentPreview` and updates the summary to reinforce that this hook is only attempting to infer preview values, and it cannot read preview values from a schema at this point.
- Are the updates accurate?
- Are the updates clear?
N/A
> docs: update useDocumentPreview reference doc

- packages/react/src/context/ComlinkTokenRefresh.tsx
Added functionality to remove the unauthorized error message from the DOM when a token is successfully refreshed. When a user's session token is refreshed, the code now checks for and removes any unauthorized error messages displayed in the `__sanityError` container, providing a cleaner user experience by eliminating stale error messages that are no longer relevant.
- The error removal logic in the token refresh flow
- The DOM manipulation approach using `document.getElementById` and element traversal
- The specific error message text being targeted for removal
Tested by:
1. Forcing a token expiration scenario
2. Verifying the unauthorized error appears in the UI
3. Confirming the error is properly removed after successful token refresh
> fix: clear error overlay on successful comlink token creation

- .env.example
- .github/workflows/e2e.yml
- apps/kitchensink-react/e2e/authenticated.spec.ts
- apps/kitchensink-react/e2e/document-editor.spec.ts
- apps/kitchensink-react/e2e/document-list.spec.ts
- apps/kitchensink-react/playwright.config.ts
- packages/@repo/e2e/README.md
- packages/@repo/e2e/src/fixtures.ts
- packages/@repo/e2e/src/helpers/clients.ts
- packages/@repo/e2e/src/helpers/getE2EEnv.ts
- packages/@repo/e2e/src/helpers/pageContext.ts
- packages/@repo/e2e/src/index.ts
- packages/@repo/e2e/src/setup/auth.setup.ts
- turbo.json
This PR adds a number of helpers and additional logic to ensure that e2e tests can work both in a standalone context as well as in the Dashboard. It adds an additional Playwright project that runs its tests in the Dashboard, as well as an additional fixture to ensure we can target elements both inside and outside of an iframe.
- I've removed the "local dev" method to authenticate e2e tests using a user token. Since local devs will also run the Dashboard test project, they would not be able to effectively sign into Dashboard with just that token. I apologize for making this more complicated.
- Does the pageContext fixture make sense?
- Any other specific logic that might be obscure to future devs?
`dashboard-chromium` runs tests within the dashboard. I'll add a test for something like …
> test(e2e): run e2e test suite in Dashboard

- packages/core/src/query/queryStore.test.ts
- packages/core/src/releases/releasesStore.test.ts
- packages/react/src/components/SanityApp.test.tsx
- packages/react/src/context/ResourceProvider.test.tsx
- packages/react/src/hooks/dashboard/useManageFavorite.test.ts
- packages/react/src/hooks/dashboard/useNavigateToStudioDocument.test.ts
- packages/react/src/hooks/dashboard/useRecordDocumentHistoryEvent.test.ts
Improved test cleanup and mocking practices across the codebase to prevent test pollution and ensure more reliable test runs. This PR addresses several issues:
1. Added proper spy cleanup with `mockRestore()` after tests
2. Moved console spies into test setup to ensure they're properly initialized
3. Added missing `listen` mock in queryStore tests
4. Fixed async act warnings in React tests by wrapping promise resolutions in `act()`
5. Added missing `useRealTimers()` call to prevent timer leakage
- Check that all console spies are properly restored after tests
- Verify that React component tests properly use `act()` for async operations
- Confirm that the queryStore tests now correctly mock the `listen` method
- run `pnpm test` with `main` branch see stderr output
- run this branch `pnpm …
> chore(tests): reduce stderr output while running tests

- knip.config.ts
- packages/core/package.json
- packages/core/src/presence/bifurTransport.test.ts
- packages/core/src/presence/bifurTransport.ts
- packages/core/src/presence/types.ts
- pnpm-lock.yaml
Added a new Bifur transport implementation for presence functionality. This implementation uses the `@sanity/bifur-client` package to establish WebSocket connections for real-time presence updates. The transport handles various presence events including state changes, disconnects, and roll calls.
- The new `bifurTransport.ts` file which implements the `PresenceTransport` interface
- The handling of different message types (state, disconnect, rollCall)
- The WebSocket connection setup and configuration
- The transformation of Bifur messages to transport events
The implementation follows the existing transport interface pattern. Tests should verify:
- Proper connection to the Bifur client
- Correct handling of incoming messages
- Proper dispatching of outgoing messages
- Session management
> feat: add bifur dependency and presence events

- apps/kitchensink-react/playwright.config.ts
- packages/@repo/e2e/src/setup/auth.setup.ts
The Dashboard has changed and is no longer idle (probably has an open connection). This removes an unnecessary wait for an idle network during authenticating to the Dashboard for Dashboard e2e tests.
Although this wasn't the problem, this also removes an unnecessary server startup in CI, since we start the server manually. (The original reason for having a separate step for preview was because the playwright tests would start running before the server was ready to respond.)
Any gotchas? Is this making things opaque?
Not quite sure what to additionally test here.
> test: do not wait for network idle when logging in during e2e auth

- knip.config.ts
- package.json
- packages/core/src/_exports/index.ts
- packages/core/src/users/reducers.ts
- packages/core/src/users/types.ts
- packages/core/src/users/usersConstants.ts
- packages/core/src/users/usersStore.test.ts
- packages/core/src/users/usersStore.ts
Added functionality to fetch and resolve individual users by ID in the users store. This includes support for both global-scoped and project-scoped user IDs, with appropriate API handling for each type. Also added a new `test:coverage:open` script to easily view coverage reports.
- New exports in `packages/core/src/_exports/index.ts` for user-related functions and types
- Implementation of `getUserState` and `resolveUser` functions in `usersStore.ts`
- Updated types to support fetching individual users
- Tests for the new user fetching functionality
- Configuration updates to support the new coverage report script
Added comprehensive tests for the new user fetching functionality, including tests for both global-scoped and project-scoped user IDs. The tests verify that the correct API …
> feat(core): allow a userId option for the user store

- packages/core/src/auth/authStore.ts
- packages/core/src/auth/refreshStampedToken.test.ts
- packages/core/src/auth/refreshStampedToken.ts
If a browser is idle then the rxJS `timer` function is not reliable.
This PR improves token refresh handling by:
1. Adding a `lastTokenRefresh` timestamp to the `LoggedInAuthState` type
2. Implementing a visibility-aware token refresh mechanism that refreshes tokens when the tab becomes visible
3. Adding a `shouldRefreshToken` function to determine if a token needs refreshing based on time elapsed
4. Optimizing token refresh logic to prevent unnecessary refreshes
These changes ensure tokens are refreshed appropriately when users return to the application after it's been in the background, improving authentication reliability.
- The new `lastTokenRefresh` property in the `LoggedInAuthState` type
- The visibility change event handler implementation
- The token refresh logic that now …
> feat(auth): check for stamped token expiration after browser idle

- packages/react/src/components/SanityApp.test.tsx
- packages/react/src/components/SanityApp.tsx
This PR adds support for disabling the automatic redirect to core when the app is not running in an iframe by introducing a `studioMode.enabled` configuration option. When this option is set to `true`, the app will not redirect to core even if it's not running in an iframe and is not a local URL.
- The updated redirect logic in `SanityApp.tsx` that now checks for `primaryConfig?.studioMode?.enabled`
- The new test case that verifies the app doesn't redirect when `studioMode.enabled` is true
Added a new test case that specifically tests the behavior when `studioMode.enabled` is set to `true`. The test verifies that no redirect occurs in this scenario, even when the app is not in an iframe and not on a local URL.
> fix: do not redirect to the Dashboard if studioMode is specified

- packages/core/src/_exports/index.ts
- packages/core/src/utils/defineIntent.test.ts
- packages/core/src/utils/defineIntent.ts
FIXES SDK-525
This PR adds a `defineIntent` function. Like `defineType`, it's mostly there as a type helper for our users, but should also hopefully provider helpful validation and error states when intents are declared.
I also plan on using this in the CLI, to be used if people declare intents as bare objects (we can use this to validate / normalize).
Mostly should be self-explanatory. Two questions:
1. are we happy where this is located (in core) and its place in the file structure (in utils?)
2. does the filters system make sense? Any gotchas there?
100% test coverage, mostly for the error scenarios.
> feat(core): add defineIntent

- release-please-config.json
Changed the versioning strategy in release-please-config.json from "always-bump-patch" to "default" for both the API and core packages. This allows for more standard semantic versioning behavior rather than always incrementing the patch version.
- Verify that changing from "always-bump-patch" to "default" versioning is the intended behavior for both packages
The release-please tool will use these settings during the next release cycle.
> fix: change versioning strategy to "default"

- apps/kitchensink-react/e2e/multi-resource.spec.ts
- apps/kitchensink-react/src/DocumentCollection/MultiResourceRoute.tsx
- packages/react/src/hooks/preview/useDocumentPreview.tsx
- packages/react/src/hooks/projection/useDocumentProjection.ts
There was some crossed wires / oversight in a few hooks, so passing in a `documentHandle` with a specific `projectId` or `dataset` wouldn't necessarily pull up the correct `SanityInstance`.
This PR fixes that and adds those hooks to the MultiResourceRoute and an e2e test. 
The actual important changes are in the react package -- it's a 2 line change. The rest is just future-proofing :)
Added e2e tests/
> fix(react): find correct instance for hooks that use config

- packages/core/src/projects/projects.test.ts
- packages/core/src/projects/projects.ts
- packages/react/src/hooks/projects/useProjects.test.ts
- packages/react/src/hooks/projects/useProjects.ts
- Add optional organizationId parameter for filtering projects by organization
- Add optional includeMembers parameter
- Implement parameter-based caching with unique cache keys
The changes to the projects fetcher store in `projects.ts` which now supports filtering by organization and toggling member inclusion. The cache key generation now incorporates these parameters to ensure proper caching behavior.
The updated type definitions in `useProjects.ts` that reflect the new parameter options and return types.
Added test coverage for the parameter passing behavior. The test in `projects.test.ts` now verifies that the correct parameters are passed to the list method.
> feat(projects): add organizationId and includeMembers parameters to useProjects hook

- apps/kitchensink-react/src/AppRoutes.tsx
- apps/kitchensink-react/src/routes/ProjectsRoute.tsx
- packages/react/src/hooks/projects/useProjects.ts
Improved the `useProjects` hook documentation and type definitions to better support the `includeMembers` parameter, making it clearer when the hook returns projects with or without member information.
Also added a new Projects route to the kitchensink-react app that displays projects available to the current user. The route allows filtering projects by organization ID and toggling the inclusion of member information.
- The improved type definitions and documentation for the `useProjects` hook
- The new `ProjectsRoute.tsx` component that displays project information
- The route registration in `AppRoutes.tsx`
Tested the new route by verifying:
- Projects display correctly with and without the organization filter
- The member information toggle works as expected
- The route is accessible …
> fix(projects): properly type the includeMembers option

- apps/kitchensink-react/sanity.cli.ts
This PR extends the Sanity CLI configuration in the kitchensink-react app to integrate with the app's Vite configuration. It adds a `vite` function that merges the app's Vite config with Sanity CLI's internal Vite config, handling plugin deduplication and ensuring React Refresh isn't injected twice. The implementation carefully merges plugins, resolve aliases, define variables, and server settings.
- The plugin merging logic that prevents duplicates and avoids double React Refresh injection
- The resolution of the app's Vite config and proper merging with Sanity CLI's config
- The handling of different configuration sections (plugins, resolve, define, server)
- The TypeScript types imported from Vite
This change should be tested by running the kitchensink-react app in both development and …
> chore: merge kitchensink's Vite config into CLI config
